version: "3.7"
name: itflow
services:
    mysql:
        container_name: mysql
        image: mysql:5.7.30
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: bug
        volumes:
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
        ports:
        - 127.0.0.1:3306:3306
        restart: always
        networks:
            - bug_network
    front:
        container_name: front
        command: 'npm run dev'
        image: vue
        environment:
            API_DOMAIN: http://127.0.0.1:10001
        volumes:
            - E:\\code\\ITflow:/data/dist
        networks:
            - bug_network
        
    # backend:
    #     container_name: backend
    #     image: vue
    #     volumes:
    #         - E:\\code\\ITflow\\go:/data/

    #     networks:
    #         - bug_network
volumes:
    - front

    
    