version: "3.7"
services:
    mysql:
        container_name: mysql
        command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci "
        image: mysql:5.7.30
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: bug
        volumes:
            - ./mysql/conf:/etc/mysql/conf.d
            - ./mysql/data:/var/lib/mysql
            - ./go/bug.sql:/bug.sql
        ports:
        - 3306:3306
        # entrypoint: "mysql -u root -p${MYSQL_ROOT_PASSWORD} < bug.sql"
        restart: always
    